### ISSUE TITLE
Feature: default favicon

### ISSUE THREAD

**Issue by stefanpante** [digipolisantwerp/starter-kit-react_app_nodejs#16]
When the app is generated, the default favicon is the react favicon.
Because this generator is used for antwerp/digipolis/acpaas apps, It would be a nice feature to have the favicon based on the chosen branding.

for more information:

https://github.com/a-ui/core_branding_favicons

https://github.com/a-ui/digipolis_branding_favicons

**Comment by TriangleJuice** [comment]
Added in #19
