### ISSUE TITLE
'serviceWorker module not found' compile error when I try to run a created app

### ISSUE THREAD

**Issue by lievenvg** [digipolisantwerp/starter-kit-react_app_nodejs#18]
I created a basic frontend app (no backend) with Antwerp styling and a Flexbox Grid.
But when I try to start the app with `npm start`, I get 
`Failed to compile.

Error in ./src/index.js
Module not found: ./serviceWorker in /Users/.../react-test-app/frontend/src
@ ./src/index.js 19:21-47`

Which is correct, there is no serviceWorker folder.

Environment:
OS: macOS Mojave (Version 10.14.5)
Node v8.9.4
NPM v5.6.0

**Comment by TriangleJuice** [comment]
Hi @lievenvg, can you provide us with all the questionnaire options you used, so we can try to reproduce the problem? TIA!

**Comment by lievenvg** [comment]
@TriangleJuice 
As suggested I upgraded Node to `v10.15.3` and NPM to `6.4.1`.
Now everything works correctly. 👌 
This ticket can be closed.
